import { Book, Category } from '../types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Tümü' },
  { id: '2', name: 'Popüler' },
  { id: '3', name: 'Yeni' },
  { id: '4', name: 'Roman' },
  { id: '5', name: 'Bilim' },
  { id: '6', name: 'Tarih' },
  { id: '7', name: 'Klasikler' },
  { id: '8', name: 'Bilim Kurgu' },
  { id: '9', name: 'Polisiye' },
  { id: '10', name: 'Kişisel Gelişim' },
];

// Gerçek çalışan ses dosyaları (test amaçlı)
const AUDIO_URLS = {
  song1: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  song2: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  song3: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  song4: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  song5: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  song6: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  song7: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
  song8: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
  song9: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
  song10: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
};

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Küçük Prens',
    author: 'Antoine de Saint-Exupéry',
    narrator: 'Hayri Küçükdeniz',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    duration: '1sa 54dk',
    rating: 4.9,
    category: 'Çocuk Klasikleri',
    description: 'Küçük Prens, Antoine de Saint-Exupéry\'nin en ünlü eseridir. Bir çocuğun gözünden büyüklerin dünyasını anlatan bu masal, evrensel bir klasik haline gelmiştir.',
    chapters: [
      { id: '1-1', title: 'Bölüm 1: Çölde Karşılaşma', duration: '12dk', audioUrl: AUDIO_URLS.song1 },
      { id: '1-2', title: 'Bölüm 2: Küçük Gezegen', duration: '15dk', audioUrl: AUDIO_URLS.song2 },
      { id: '1-3', title: 'Bölüm 3: Gül ve Tilki', duration: '18dk', audioUrl: AUDIO_URLS.song3 },
    ],
    isDownloaded: true,
    progress: 45,
    lastPlayedAt: new Date(),
  },
  {
    id: '2',
    title: '1984',
    author: 'George Orwell',
    narrator: 'Mehmet Atay',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    duration: '11sa 24dk',
    rating: 4.9,
    category: 'Bilim Kurgu',
    description: 'George Orwell\'in distopya klasiklerinden biri olan 1984, totaliter bir toplumda yaşamanın korkunçluğunu anlatır.',
    chapters: [
      { id: '2-1', title: 'Bölüm 1: Büyük Birader', duration: '25dk', audioUrl: AUDIO_URLS.song4 },
      { id: '2-2', title: 'Bölüm 2: Hakikat Bakanlığı', duration: '28dk', audioUrl: AUDIO_URLS.song5 },
      { id: '2-3', title: 'Bölüm 3: Winston\'ın Günlüğü', duration: '22dk', audioUrl: AUDIO_URLS.song6 },
    ],
    isDownloaded: false,
    downloadProgress: 15,
  },
  {
    id: '3',
    title: 'Dune',
    author: 'Frank Herbert',
    narrator: 'Ali Vural',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    duration: '21sa 02dk',
    rating: 4.8,
    category: 'Bilim Kurgu',
    chapters: [
      { id: '3-1', title: 'Bölüm 1: Arrakis', duration: '30dk', audioUrl: AUDIO_URLS.song7 },
      { id: '3-2', title: 'Bölüm 2: Baharat', duration: '35dk', audioUrl: AUDIO_URLS.song8 },
    ],
  },
  {
    id: '4',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    narrator: 'Can Yücel',
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
    duration: '15sa 17dk',
    rating: 4.9,
    category: 'Bilim',
    chapters: [
      { id: '4-1', title: 'Bölüm 1: Bilişsel Devrim', duration: '20dk', audioUrl: AUDIO_URLS.song9 },
      { id: '4-2', title: 'Bölüm 2: Tarım Devrimi', duration: '25dk', audioUrl: AUDIO_URLS.song10 },
    ],
  },
  {
    id: '5',
    title: 'Suç ve Ceza',
    author: 'Fyodor Dostoyevski',
    narrator: 'Hayri Küçükdeniz',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
    duration: '24sa 45dk',
    rating: 4.7,
    category: 'Klasikler',
    description: 'Fyodor Dostoyevsky\'nin başyapıtı Suç ve Ceza, yoksul bir öğrenci olan Raskolnikov\'un hikayesini anlatır.',
    chapters: [
      { id: '5-1', title: 'Bölüm 1: Fikir', duration: '35dk', audioUrl: AUDIO_URLS.song1 },
      { id: '5-2', title: 'Bölüm 2: Cinayet', duration: '40dk', audioUrl: AUDIO_URLS.song2 },
      { id: '5-3', title: 'Bölüm 3: Sonya', duration: '38dk', audioUrl: AUDIO_URLS.song3 },
    ],
    isDownloaded: true,
    progress: 78,
  },
  {
    id: '6',
    title: 'Dönüşüm',
    author: 'Franz Kafka',
    narrator: 'Zeynep Özkan',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    duration: '2sa 12dk',
    rating: 4.8,
    category: 'Klasikler',
    description: 'Gregor Samsa bir sabah uyandığında kendini dev bir böceğe dönüşmüş bulur.',
    chapters: [
      { id: '6-1', title: 'Bölüm 1: Dönüşüm', duration: '45dk', audioUrl: AUDIO_URLS.song4 },
      { id: '6-2', title: 'Bölüm 2: Aile', duration: '40dk', audioUrl: AUDIO_URLS.song5 },
      { id: '6-3', title: 'Bölüm 3: Son', duration: '35dk', audioUrl: AUDIO_URLS.song6 },
    ],
    isDownloaded: true,
    isCompleted: true,
  },
  {
    id: '7',
    title: 'Sırça Köşk',
    author: 'Sabahattin Ali',
    narrator: 'Ayşe Demir',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400',
    duration: '3sa 30dk',
    rating: 4.9,
    category: 'Roman',
    chapters: [
      { id: '7-1', title: 'Bölüm 1', duration: '20dk', audioUrl: AUDIO_URLS.song7 },
      { id: '7-2', title: 'Bölüm 2', duration: '22dk', audioUrl: AUDIO_URLS.song8 },
      { id: '7-3', title: 'Bölüm 3', duration: '25dk', audioUrl: AUDIO_URLS.song9 },
      { id: '7-4', title: 'Bölüm 4: Sırça Köşk', duration: '28dk', audioUrl: AUDIO_URLS.song10 },
    ],
    progress: 58,
  },
  {
    id: '8',
    title: 'Kürk Mantolu Madonna',
    author: 'Sabahattin Ali',
    narrator: 'Ayşe Demir',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    duration: '5sa 24dk',
    rating: 4.9,
    category: 'Roman',
    chapters: [
      { id: '8-1', title: 'Bölüm 1: Berlin', duration: '30dk', audioUrl: AUDIO_URLS.song1 },
      { id: '8-2', title: 'Bölüm 2: Maria Puder', duration: '35dk', audioUrl: AUDIO_URLS.song2 },
    ],
  },
  {
    id: '9',
    title: 'Nutuk',
    author: 'Mustafa Kemal Atatürk',
    narrator: 'Mehmet Özgür',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    duration: '34sa 12dk',
    rating: 5.0,
    category: 'Tarih',
    chapters: [
      { id: '9-1', title: 'Giriş', duration: '45dk', audioUrl: AUDIO_URLS.song3 },
      { id: '9-2', title: 'Bölüm 1: Samsun\'a Çıkış', duration: '50dk', audioUrl: AUDIO_URLS.song4 },
    ],
  },
  {
    id: '10',
    title: 'Harry Potter ve Felsefe Taşı',
    author: 'J.K. Rowling',
    narrator: 'Zeynep Özkan',
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
    duration: '9sa 33dk',
    rating: 4.9,
    category: 'Fantastik',
    chapters: [
      { id: '10-1', title: 'Bölüm 1: Hayatta Kalan Çocuk', duration: '25dk', audioUrl: AUDIO_URLS.song5 },
      { id: '10-2', title: 'Bölüm 2: Kaybolan Cam', duration: '20dk', audioUrl: AUDIO_URLS.song6 },
      { id: '10-3', title: 'Bölüm 3: Bilinmeyen Mektuplar', duration: '22dk', audioUrl: AUDIO_URLS.song7 },
    ],
    isDownloaded: true,
    progress: 78,
  },
];

export const featuredBook: Book = mockBooks[0];

export const popularBooks: Book[] = [
  mockBooks[1],
  mockBooks[2],
  mockBooks[3],
  mockBooks[4],
];
